Repository wadhah101/insat-gl-knowledge, pull requests merged in 2022-11, with the labels that each got.

#33 23 add complexity theory chapters
  docs/GL3/Complexity Theory/advanced.md
  docs/GL3/Complexity Theory/complexity.md
  docs/GL3/Complexity Theory/fibonacci.md
  docs/GL3/Complexity Theory/iterative.md
  docs/GL3/Complexity Theory/recursion.md
Labels: documentation

#45 22 add data analysis chapters
  docs/GL4/Data Analysis/advanced-continuous-distributions.md
  docs/GL4/Data Analysis/advanced-discrete-distributions.md
  docs/GL4/Data Analysis/advanced.md
  docs/GL4/Data Analysis/conjoint.md
  docs/GL4/Data Analysis/continuous-distributions.md
  docs/GL4/Data Analysis/discrete-distributions.md
  docs/GL4/Data Analysis/formalisation.md
  docs/GL4/Data Analysis/introduction.md
  docs/GL4/Data Analysis/medium-continuous-distributions.md
  docs/GL4/Data Analysis/regression.md
  docs/GL4/Data Analysis/statistics.md
Labels: question

#58 New content and some changes
  docs/GL2/Semester 2/Unix/DS/2020.md
  docs/GL3/Semester 1/Complexity Theory/assets/fib-exp-comp-01.png
  docs/GL3/Semester 1/Complexity Theory/assets/fib-exp-comp-02.png
  docs/GL3/Semester 1/Complexity Theory/assets/fib-exp-comp-03.png
  docs/GL3/Semester 1/Complexity Theory/assets/fib-exp-comp-04.png
  docs/GL3/Semester 1/Complexity Theory/fibonacci-explicit-complexity.md
  docs/GL3/Semester 1/System Modelisation/Exams/2018.md
  docs/GL3/Semester 1/System Modelisation/Exams/assets/2018-1.jpg
  docs/GL3/Semester 1/System Modelisation/Exams/assets/2018-2.jpg
  docs/GL3/Semester 1/System Modelisation/Exams/assets/2018-c-1.jpg
  docs/GL3/Semester 1/System Modelisation/Exams/assets/2018-c-2.jpg
  docs/GL3/Semester 1/System Modelisation/Exams/assets/2018-c-3.jpg
  docs/GL3/Semester 1/System Modelisation/Exams/assets/2018-c-4.jpg
  docs/GL3/Semester 2/Advanced Algorithms/b-tree.md
  docs/GL3/Semester 2/Advanced Algorithms/heap.md
  docs/GL3/Semester 2/Distributed Systems/assets/App_design.png
  docs/GL3/Semester 2/Distributed Systems/tp-bo-and-ho-offices.md
  docs/GL3/Semester 2/Logic programming/cheat-sheets/version-haj-ali.md
  docs/GL3/Semester 2/Logic programming/cheat-sheets/version-saif.md
  docs/GL5/Semester 1/Deep Learning/assets/output_10_1.png
  docs/GL5/Semester 1/Deep Learning/assets/output_14_1.png
  docs/GL5/Semester 1/Deep Learning/assets/output_15_0.png
  docs/GL5/Semester 1/Deep Learning/assets/output_18_1.png
  docs/GL5/Semester 1/Deep Learning/assets/output_19_0.png
  docs/GL5/Semester 1/Deep Learning/assets/output_3_1.png
  docs/GL5/Semester 1/Deep Learning/assets/output_6_1.png
  docs/GL5/Semester 1/Deep Learning/linear-reg.md
Labels: documentation, enhancement
